version: 1.0.{build}
image: Visual Studio 2022
environment:
  SONARCLOUD_TOKEN:
      secure: VS2sS9yIjj8hIYWyp4460eAh0tSenN3plfajevcasZvGA72w6a2/GO+L5bzEoV81
before_build:
 - cmd: cd backend && nuget restore
build_script:
 - dir "C:\Program Files\Java"
 - echo %JAVA_HOME%
 - set JAVA_HOME=C:\Program Files\Java\jdk17
 - set PATH=%JAVA_HOME%\bin;%PATH%
 - echo %PATH%
 - cd C:\projects\energy-management-system\backend
 - choco install "sonarscanner-msbuild-net46" -y
 - SonarScanner.MSBuild.exe begin /k:"energy-management-system" /d:"sonar.host.url=https://sonarcloud.io" /o:"pieterh" /d:"sonar.login=%SONARCLOUD_TOKEN%" /d:"sonar.cs.vstest.reportsPaths=**\TestResults\*.trx" /d:"sonar.cs.opencover.reportsPaths=**/coverage.cobertura.xml" /d:"sonar.coverage.exclusions=**/*Tests.cs" /d:"sonar.exclusions=**/*Tests.cs" /d:"sonar.tests.exclusions=**/*Tests.cs"
 - msbuild /verbosity:quiet "ems.sln"
 - dotnet test --logger "trx;LogFileName=TestResults.trx" --collect:"XPlat Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover,cobertura
 - SonarScanner.MSBuild.exe end /d:"sonar.login=%SONARCLOUD_TOKEN%"
