@apiRoot = http://localhost:5000

####
GET {{apiRoot}}/api/mydemo?id=12 HTTP/1.1


####

POST {{apiRoot}}/api/users/authenticate HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}


####

GET {{apiRoot}}/api/users/ping HTTP/1.2
content-type: application/json
cookie: X-Access-Token=eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4NDM2ODkyOC1mZTk3LTRhZmUtYmNhYS01MTVkNTljOWZlMjQiLCJ0eXAiOiJKV1QiLCJzdWIiOiI1MWQxZDU3ZS1hYTVkLTRkZDgtYmEwMy03MGZmODk3ODJmNDEiLCJuYW1lIjoiUGlldGVyIEhpbGtlbWVpamVyIiwiZXhwIjoxNjE5ODExMjc1LCJpc3MiOiJodHRwOi8vcGV0dGVmbGV0Lm9yZyIsImF1ZCI6IlRlc3QifQ.w7DmE93RBz1u6v0wq9YpvMfJ3qOUgFGgknPHzUM_qi2CsnQR0cVvlnTzPOCjwfnva5rgbK-JWYgIzEmDlcdrQkvtOBRQwAaOhv9dtGRuWahWAy5fV2U5_BAMS3QNLyyejo8hrpZdvTChU5Rlyt4Vwahv0XDrXlEAwe7HYuR0TSphlbtR9ptelqC7joy-wfD0Vgqn9WEgfbrf_Xx9zdh7JbgJ4EtFJRMglVUB61VxmtjCtSkwXZCe_j-f_a2cvx1huQ6qXXckJOZUkHYzxuXdFKF5Oj-WrUqJkXjN7yRiZwHqJPAxWUhJ-wwZcLStne0LeUOArlWXBZkSHO-uJjOKXQ; path=/api; samesite=strict; httponly

####

GET {{apiRoot}}/api/dashboard HTTP/1.2
content-type: application/json
cookie: X-Access-Token=eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwYTA5NjU2Mi1kZmM4LTQyY2UtYjljNS0wODk2NjNlYmUwNzYiLCJ0eXAiOiJKV1QiLCJzdWIiOiJmZDY1NjdhNS04YzU4LTRlMDAtYmJiNS04YTQ3ODAwMWNjNTEiLCJuYW1lIjoiUGlldGVyIEhpbGtlbWVpamVyIiwiZXhwIjoxNjE5ODExMzQzLCJpc3MiOiJodHRwOi8vcGV0dGVmbGV0Lm9yZyIsImF1ZCI6IlRlc3QifQ.ODbHLL7_tNqB065eX6xjxjZLZKG9wrp3oNhoXls6B3t0c1N0XpLUPbXJbKmf4usv-qzZb2V3dstqX_MTMGGHnWouwct9mgZp6RqgVYxqIbAuCqZXzOoYS9IFYZsxk3JLqqniyFceX1TSOHBxbi5mxyy9kAwpkDgwLFxnrDcUskTiFyL-7vwb2FEbeDcnRWGHXVuSD3YAF7MJg6X45nt_kGJ0Id7FTRz4BkHVTvDB26HIUcp8eaDlKQ_uQOMyIX43OU0Y_sgyEuRBZt5Hs7DY_wM_O9H36cUUdYYzu9WvP3YPTU02FwMhbZj4g7eM_GKZwD-V076o6uJn-FfWlODAgw; path=/api; samesite=strict; httponly


####