@apiRoot = http://localhost:5000
@token = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxZGQ3MDgzYy1kMDY1LTRiZTUtODE5Ni03OGRmYTYyOTFmMWIiLCJ0eXAiOiJKV1QiLCJzdWIiOiIyNmNkNjE5NS04MDI3LTQzOGQtYmFhNi05YzAyY2I3ZDQ1YTEiLCJuYW1lIjoiUGlldGVyIEhpbGtlbWVpamVyIiwiZXhwIjoxNjIwMTY0ODMyLCJpc3MiOiJoZW1zIiwiYXVkIjoiaGVtcyJ9.n94tRQPRDjCVI5Q0oOeCEIjHoMWCNkuHutE0Z9_6XrqRFovx2iZ-QJRGwxHWMb946Z8WDpqh_59QSCiEHRPjC_wcBaGoxLF3fPqq_gAbX9srtt01g9jzYiiqXYTxSS6_mFVrpIRp9igS-oFIQgXI2GWAV-ZqCZ9qEyLknOq-UHoz2h1lZDzVwS4rV77G88AZ4UK7pG-2e18lU-qY2D2G9EjMWebipgsTcCKkiS4gS1EnDESfwQrBljjPeiy90LydYbs3KoJjxMT8yYnGSpXxV038SR7oVgcociCYbrtdS9N0aSASpvmzt2IVqwyFcvxPUTD7-xFBnnZ5CRyk5HprFQ


####
GET {{apiRoot}}/api/mydemo?id=12 HTTP/1.1
Authorization: Bearer {{token}}

####

POST {{apiRoot}}/api/users/authenticate HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}


####

GET {{apiRoot}}/api/users/ping HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

####

GET {{apiRoot}}/api/dashboard HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

#####

//cookie: X-Access-Token=eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwYTA5NjU2Mi1kZmM4LTQyY2UtYjljNS0wODk2NjNlYmUwNzYiLCJ0eXAiOiJKV1QiLCJzdWIiOiJmZDY1NjdhNS04YzU4LTRlMDAtYmJiNS04YTQ3ODAwMWNjNTEiLCJuYW1lIjoiUGlldGVyIEhpbGtlbWVpamVyIiwiZXhwIjoxNjE5ODExMzQzLCJpc3MiOiJodHRwOi8vcGV0dGVmbGV0Lm9yZyIsImF1ZCI6IlRlc3QifQ.ODbHLL7_tNqB065eX6xjxjZLZKG9wrp3oNhoXls6B3t0c1N0XpLUPbXJbKmf4usv-qzZb2V3dstqX_MTMGGHnWouwct9mgZp6RqgVYxqIbAuCqZXzOoYS9IFYZsxk3JLqqniyFceX1TSOHBxbi5mxyy9kAwpkDgwLFxnrDcUskTiFyL-7vwb2FEbeDcnRWGHXVuSD3YAF7MJg6X45nt_kGJ0Id7FTRz4BkHVTvDB26HIUcp8eaDlKQ_uQOMyIX43OU0Y_sgyEuRBZt5Hs7DY_wM_O9H36cUUdYYzu9WvP3YPTU02FwMhbZj4g7eM_GKZwD-V076o6uJn-FfWlODAgw; path=/api; samesite=strict; httponly


####