
from mcr.microsoft.com/dotnet/aspnet:latest

RUN mkdir /app
RUN mkdir /app/ems
RUN mkdir /app/ems/dist

COPY backend/EMS/bin/Release/net7.0/ /app/ems/
RUN rm -f -R /app/ems/dist/*
COPY frontend/EMS.ReactApp/dist/ /app/ems/dist/
RUN chmod -R ugo+x /app

RUN rm /app/ems/NLog.config
RUN rm /app/ems/config.json

RUN ls -la /app/ems
RUN ls -la /app/ems/dist

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod ugo+x /usr/local/bin/entrypoint.sh
RUN chmod ugo+r /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
