
from mcr.microsoft.com/dotnet/aspnet:latest

RUN mkdir /app
RUN mkdir /app/ems
RUN chmod ugo+x /app
RUN chmod ugo+x /app/ems
RUN chmod ugo+r /app
RUN chmod ugo+r /app/ems

COPY backend/EMS/bin/Release/net7.0/ /app/ems/
RUN rm /app/ems/NLog.config
RUN rm /app/ems/config.json
RUN ls -la /app/ems
COPY frontend/EMS.ReactApp/dist/ /app/ems/dist/
RUN ls -la /app/ems/dist
RUN ls -la /app/ems/dist/app

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod ugo+x /usr/local/bin/entrypoint.sh
RUN chmod ugo+r /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
