FROM mcr.microsoft.com/dotnet/aspnet:7.0.3

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod ugo+x /usr/local/bin/entrypoint.sh
RUN chmod ugo+r /usr/local/bin/entrypoint.sh

ARG BACKEND
ARG FEREACT

RUN mkdir /app
RUN mkdir /app/ems
RUN chmod ugo+x /app
RUN chmod ugo+x /app/ems
RUN chmod ugo+r /app
RUN chmod ugo+r /app/ems

RUN echo $BACKEND
RUN echo $FEREACT

COPY $BACKEND/ /app/ems/
RUN rm /app/ems/NLog.config
RUN rm /app/ems/config.json
RUN ls -la /app/ems

COPY $FEREACT/ /app/ems/dist/
RUN ls -la /app/ems/dist
RUN ls -la /app/ems/dist/app

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
