// <auto-generated />
using System;
using EMS.DataStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.DataStore.Migrations
{
    [DbContext(typeof(HEMSContext))]
    [Migration("20220123164338_SomeDetails")]
    partial class SomeDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("EMS.DataStore.ChargingTransaction", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<double>("EnergyDelivered")
                        .HasColumnType("REAL");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ChargingTransactions");
                });

            modelBuilder.Entity("EMS.DataStore.CostDetail", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChargingTransactionID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<double>("EnergyDelivered")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TarifStart")
                        .HasColumnType("TEXT");

                    b.Property<double>("TarifUsage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ChargingTransactionID");

                    b.ToTable("CostDetail");
                });

            modelBuilder.Entity("EMS.DataStore.CostDetail", b =>
                {
                    b.HasOne("EMS.DataStore.ChargingTransaction", null)
                        .WithMany("CostDetails")
                        .HasForeignKey("ChargingTransactionID");
                });

            modelBuilder.Entity("EMS.DataStore.ChargingTransaction", b =>
                {
                    b.Navigation("CostDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
