name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:    
    - name: Checkout
      uses: actions/checkout@v3     
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}     
    - name: Cache SonarQube packages
      uses: actions/cache@v3
      with:
        path: ./sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache SonarQube scanner
      id: cache-sonar-scanner
      uses: actions/cache@v3
      with:
        path: ./.sonar/scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
    - name: Install SonarQube scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: bash
      run: |
        pwd
        mkdir -p ./.sonar/scanner 
        dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner        
        ls -la ./.sonar/scanner
    - name: Install dependencies
      run: dotnet restore
      working-directory: backend      
    - name: SonarQube - Begin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      run: ../.sonar/scanner/dotnet-sonarscanner begin /k:"pieterh_energy-management-system" /o:"pieterh" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.branch.name="${{ github.ref_name }}" /d:"sonar.cs.vstest.reportsPaths=**/TestResults/*.trx" /d:"sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml" /d:"sonar.coverage.exclusions=**/*Tests.cs" /d:"sonar.exclusions=**/*Tests.cs" /d:"sonar.tests.exclusions=**/*Tests.cs"          
      working-directory: backend      
    - name: Build - backend
      run: dotnet build --configuration Release --no-restore
      working-directory: backend
    - name: Test - backend
      run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=TestResults.trx" --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover       
      working-directory: backend      
    - name: SonarQube - End
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      run: ../.sonar/scanner/dotnet-sonarscanner end    
      working-directory: backend      
    - name: Install yarn
      run: npm install --global yarn
      working-directory: frontend/EMS.ReactApp
    - name: Install packages using yarn and respect lock file
      run: yarn install --frozen-lockfile
      working-directory: frontend/EMS.ReactApp
    - name: Build - frontend
      run: npm run build
      working-directory: frontend/EMS.ReactApp
    - name: Build the docker image
      if: github.ref != 'refs/heads/main'
      run: |
        docker build . --file docker/dockerfile
    - name: Push the docker image
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker build . --file docker/dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest        
        docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
     
