on:
  workflow_call:
    inputs:
      docker-image-tag:
        required: true
        type: string
jobs:
  integration_tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies - backend
      run: dotnet restore
      working-directory: backend
    - name: Start docker containers
      run: |
        chmod ugo+w config         
        docker compose --file hems-integration-test-docker-compose.yml up --pull --build --detach
        sleep 15
      working-directory: docker/tests  
    - name: Build - backend
      run: |
        dotnet build --no-restore --configuration Release --verbosity normal --property WarningLevel=0
      working-directory: backend
    - name: Test - backend
      id: tests
      continue-on-error: true
      run: |
        dotnet test --filter "Category=Integration" --no-build --configuration Release --verbosity normal 
      working-directory: backend
    - name: Stop docker containers
      id: docker-stop
      continue-on-error: true
      run: |
        sleep 5
        docker logs hems-integration-test >${{ runner.temp }}/hems-integration-test-docker.log
        docker compose --file hems-integration-test-docker-compose.yml down
        echo ${{ steps.tests.outcome }}
      working-directory: docker/tests
    - name: Upload backend logs
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: backend-logs
        path: docker/tests/config/*.log 
    - name: Upload docker logs
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: hems-integration-test-docker-logs
        path: ${{ runner.temp }}/hems-integration-test-docker.log
    - name: Check on failures
      if: steps.tests.outcome == failure()
      run: |
        echo ${{ steps.tests.outcome }}
        exit 1
